window.esdocSearchIndex = [
  [
    "@dlghq/dialog-utils/src/redux/field.js~field",
    "class/src/redux/field.js~Field.html",
    "<span>Field</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/redux/field.js</span>",
    "class"
  ],
  [
    "@dlghq/dialog-utils/src/core/calculatecursor.js~calculatecursor",
    "function/index.html#static-function-calculateCursor",
    "<span>calculateCursor</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/core/calculateCursor.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/dom/filetobase64.js~filetobase64",
    "function/index.html#static-function-fileToBase64",
    "<span>fileToBase64</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/dom/fileToBase64.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/core/filterbyquery.js~filterbyquery",
    "function/index.html#static-function-filterByQuery",
    "<span>filterByQuery</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/core/filterByQuery.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/core/formattime.js~formattime",
    "function/index.html#static-function-formatTime",
    "<span>formatTime</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/core/formatTime.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/core/getreadablefilesize.js~getreadablefilesize",
    "function/index.html#static-function-getReadableFileSize",
    "<span>getReadableFileSize</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/core/getReadableFileSize.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/dom/hasselection.js~hasselection",
    "function/index.html#static-function-hasSelection",
    "<span>hasSelection</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/dom/hasSelection.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/support/iselectron.js~iselectron",
    "function/index.html#static-function-isElectron",
    "<span>isElectron</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/support/isElectron.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/support/ispassivelistenersupports.js~ispassivelistenersupports",
    "function/index.html#static-function-isPassiveListenerSupports",
    "<span>isPassiveListenerSupports</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/support/isPassiveListenerSupports.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/dom/listen.js~listen",
    "function/index.html#static-function-listen",
    "<span>listen</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/dom/listen.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/core/mapnotnull.js~mapnotnull",
    "function/index.html#static-function-mapNotNull",
    "<span>mapNotNull</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/core/mapNotNull.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/dom/selectfiles.js~selectfiles",
    "function/index.html#static-function-selectFiles",
    "<span>selectFiles</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/dom/selectFiles.js</span>",
    "function"
  ],
  [
    "@dlghq/dialog-utils/src/dom/selecttext.js~selecttext",
    "function/index.html#static-function-selectText",
    "<span>selectText</span> <span class=\"search-result-import-path\">@dlghq/dialog-utils/src/dom/selectText.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/core/__tests__/calculatecursor.js",
    "file/src/core/__tests__/calculateCursor.js.html",
    "src/core/__tests__/calculateCursor.js",
    "file"
  ],
  [
    "src/core/__tests__/filterbyquery.js",
    "file/src/core/__tests__/filterByQuery.js.html",
    "src/core/__tests__/filterByQuery.js",
    "file"
  ],
  [
    "src/core/__tests__/mapnotnull.js",
    "file/src/core/__tests__/mapNotNull.js.html",
    "src/core/__tests__/mapNotNull.js",
    "file"
  ],
  [
    "src/core/calculatecursor.js",
    "file/src/core/calculateCursor.js.html",
    "src/core/calculateCursor.js",
    "file"
  ],
  [
    "src/core/filterbyquery.js",
    "file/src/core/filterByQuery.js.html",
    "src/core/filterByQuery.js",
    "file"
  ],
  [
    "src/core/formattime.js",
    "file/src/core/formatTime.js.html",
    "src/core/formatTime.js",
    "file"
  ],
  [
    "src/core/getreadablefilesize.js",
    "file/src/core/getReadableFileSize.js.html",
    "src/core/getReadableFileSize.js",
    "file"
  ],
  [
    "src/core/mapnotnull.js",
    "file/src/core/mapNotNull.js.html",
    "src/core/mapNotNull.js",
    "file"
  ],
  [
    "src/dom/filetobase64.js",
    "file/src/dom/fileToBase64.js.html",
    "src/dom/fileToBase64.js",
    "file"
  ],
  [
    "src/dom/hasselection.js",
    "file/src/dom/hasSelection.js.html",
    "src/dom/hasSelection.js",
    "file"
  ],
  [
    "src/dom/listen.js",
    "file/src/dom/listen.js.html",
    "src/dom/listen.js",
    "file"
  ],
  [
    "src/dom/selectfiles.js",
    "file/src/dom/selectFiles.js.html",
    "src/dom/selectFiles.js",
    "file"
  ],
  [
    "src/dom/selecttext.js",
    "file/src/dom/selectText.js.html",
    "src/dom/selectText.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/redux/action.js",
    "file/src/redux/action.js.html",
    "src/redux/action.js",
    "file"
  ],
  [
    "src/redux/field.js",
    "file/src/redux/field.js.html",
    "src/redux/field.js",
    "file"
  ],
  [
    "src/redux/field.js~field#constructor",
    "class/src/redux/field.js~Field.html#instance-constructor-constructor",
    "src/redux/field.js~Field#constructor",
    "method"
  ],
  [
    "src/redux/field.js~field#error",
    "class/src/redux/field.js~Field.html#instance-member-error",
    "src/redux/field.js~Field#error",
    "member"
  ],
  [
    "src/redux/field.js~field#flatmap",
    "class/src/redux/field.js~Field.html#instance-method-flatMap",
    "src/redux/field.js~Field#flatMap",
    "method"
  ],
  [
    "src/redux/field.js~field#map",
    "class/src/redux/field.js~Field.html#instance-method-map",
    "src/redux/field.js~Field#map",
    "method"
  ],
  [
    "src/redux/field.js~field#pending",
    "class/src/redux/field.js~Field.html#instance-member-pending",
    "src/redux/field.js~Field#pending",
    "member"
  ],
  [
    "src/redux/field.js~field#render",
    "class/src/redux/field.js~Field.html#instance-method-render",
    "src/redux/field.js~Field#render",
    "method"
  ],
  [
    "src/redux/field.js~field#value",
    "class/src/redux/field.js~Field.html#instance-member-value",
    "src/redux/field.js~Field#value",
    "member"
  ],
  [
    "src/redux/field.js~field.create",
    "class/src/redux/field.js~Field.html#static-method-create",
    "src/redux/field.js~Field.create",
    "method"
  ],
  [
    "src/redux/field.js~field.dispatch",
    "class/src/redux/field.js~Field.html#static-method-dispatch",
    "src/redux/field.js~Field.dispatch",
    "method"
  ],
  [
    "src/support/iselectron.js",
    "file/src/support/isElectron.js.html",
    "src/support/isElectron.js",
    "file"
  ],
  [
    "src/support/ispassivelistenersupports.js",
    "file/src/support/isPassiveListenerSupports.js.html",
    "src/support/isPassiveListenerSupports.js",
    "file"
  ]
]